languageCode = 'en-us'
title = "Owen's Blog"
theme = 'PaperMod'
[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Owen's Blog"
description = "Ramblings about tech, leadership and open source"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Me"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

[params.label]
text = "obowersa"
iconHeight = 35

[params.profileMode]
enabled = true
title = "Owen's Blog"
subtitle = "Ramblings about tech, leadership and all things open source"
imageUrl = "/owen.png"
imageWidth = 320
imageHeight = 320
imageTitle = "Owen"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Notes"
url = "notes"


[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[[params.profileMode.buttons]]
name = "About"
url = "about"

[params.homeInfoParams]
Title = "Hi there"
Content = "Welcome to my blog"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/obowersa"

[[params.socialIcons]]
name = "github"
url = "https://github.com/obowersa"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/obowersa/"


[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/obowersa/obowersa.net/content"
Text = "Suggest Changes"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 5

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30
